import React, {useState, useEffect} from 'react';
import Head from 'next/head';
import * as S from '../styles/home';
import NavBar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { relative } from 'path';
import IntroProjetos from '@/components/IntroProjetos';


const Home = () => {

    const projetos = [
        { nome: 'Baratão Supermercados' },
        { nome: 'Sessão de fotos - cliente' },
      ];

    return (
        <>
            <Head>
                <title>Agil Mob</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <NavBar/>
            <S.Main>                
                <S.ContainerFoto>
                    <S.ImagemInicial src='/Ativo 8.png'></S.ImagemInicial>
                    <S.divSpan>
                        <S.SpanImagemInicial>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</S.SpanImagemInicial>
                    </S.divSpan>
                </S.ContainerFoto>
                {projetos.map((projeto, index) => (
                <IntroProjetos key={index} nome={projeto.nome} />
                ))}
            </S.Main>
            <Footer/>
        </>
    );
}

export default Home;

